#!/usr/bin/env python3
"""
Agent Scaffold Script — generate a production-grade Agent project.

Usage:
    python init_agent.py <agent-name> [--level 0-4] [--path <output-dir>]

Examples:
    python init_agent.py my-agent                 # Level 1 (4 tools, production base)
    python init_agent.py my-agent --level 0       # Agent loop + bash only
    python init_agent.py my-agent --level 2       # + TodoWrite planning
    python init_agent.py my-agent --level 3       # + Subagent
    python init_agent.py my-agent --level 4       # + Skill loading
    python init_agent.py my-agent --path ./bots   # Custom output directory

Levels (production-grade, not line-count based):
    0  Agent loop + bash            — the minimum viable agent
    1  + read/write/edit tools      — production base: config, logging, retry,
                                      permission checkpoint, trajectory capture
    2  + TodoWrite                  — plan first, then execute
    3  + Subagent                   — isolated context for subtasks
    4  + Skill loading              — on-demand domain knowledge

Each level generates a full project directory:
    <name>/agent.py, config.yaml, .env.example, requirements.txt, README.md
"""

import argparse
import sys
from pathlib import Path

# ===========================================================================
# Generated agent.py — common header (config, logging, Tool, validation)
# ===========================================================================

COMMON_HEADER = '''#!/usr/bin/env python3
"""
{name} — production Agent (level {level}: {level_desc})

Generated by init_agent.py. Customize TOOL_SPECS and SYSTEM_PROMPT for your domain.

Run:  python agent.py
Need: pip install anthropic python-dotenv pyyaml + .env with ANTHROPIC_API_KEY
"""

from __future__ import annotations

import json
import logging
import os
import signal
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import yaml
from anthropic import Anthropic, APIStatusError, APITimeoutError, APIConnectionError
from dotenv import load_dotenv

load_dotenv(override=True)

WORKDIR = Path.cwd().resolve()
LOG = logging.getLogger("agent")
TRAJECTORY_DIR = WORKDIR / ".trajectories"


def load_config() -> dict:
    """Load optional declarative config; env vars take precedence."""
    config = {{
        "model": os.getenv("MODEL_ID", "claude-sonnet-4-6"),
        "max_tokens": int(os.getenv("MAX_TOKENS", "8000")),
        "timeout_seconds": float(os.getenv("TIMEOUT_SECONDS", "120")),
        "max_retries": int(os.getenv("MAX_RETRIES", "3")),
        "base_delay_seconds": float(os.getenv("BASE_DELAY_SECONDS", "0.5")),
    }}
    config_path = WORKDIR / "config.yaml"
    if config_path.exists():
        with config_path.open(encoding="utf-8") as handle:
            file_config = yaml.safe_load(handle) or {{}}
        if isinstance(file_config, dict):
            for key, value in file_config.items():
                config.setdefault(key, value)
    return config


CONFIG = load_config()
client = Anthropic(base_url=os.getenv("ANTHROPIC_BASE_URL"))


@dataclass
class Tool:
    """One action the agent can take. Side effect and permission are explicit."""

    name: str
    description: str
    input_schema: dict
    handler: Callable[..., str]
    permission: str = "allow"  # allow | ask | deny


def _require_string(value: Any, field: str) -> str:
    if not isinstance(value, str):
        raise ValueError(f"{{field}} must be a string")
    return value


def _validate_input(tool: Tool, args: dict) -> dict:
    """Validate tool input against its JSON schema (required fields + types)."""
    props = tool.input_schema.get("properties", {{}})
    required = tool.input_schema.get("required", [])
    for field_name in required:
        if field_name not in args:
            raise ValueError(f"Missing required field: {{field_name}}")
    for key, value in args.items():
        spec = props.get(key, {{}})
        expected = spec.get("type")
        if expected == "string":
            _require_string(value, key)
        elif expected == "integer" and not isinstance(value, int):
            raise ValueError(f"{{key}} must be an integer")
        elif expected == "number" and not isinstance(value, (int, float)):
            raise ValueError(f"{{key}} must be a number")
        elif expected == "boolean" and not isinstance(value, bool):
            raise ValueError(f"{{key}} must be a boolean")
    return args


def safe_path(path: str, base: Path | None = None) -> Path:
    """Resolve a path and refuse to escape the workspace (fail closed)."""
    base = (base or WORKDIR).resolve()
    resolved = (base / path).resolve()
    if not resolved.is_relative_to(base):
        raise ValueError(f"Path escapes workspace: {{path}}")
    return resolved
'''

# ===========================================================================
# Tool handlers per level
# ===========================================================================

HANDLER_BASH = '''

def _tool_bash(command: str) -> str:
    """Execute a shell command with timeout; return combined output."""
    try:
        result = subprocess.run(
            command, shell=True, cwd=WORKDIR,
            capture_output=True, text=True,
            timeout=CONFIG["timeout_seconds"],
        )
        output = (result.stdout + result.stderr).strip()
        if result.returncode != 0:
            return f"Error: exit {result.returncode}\\n{output or '(no output)'}"
        return output or "(no output)"
    except subprocess.TimeoutExpired:
        return "Error: Timeout"
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"
'''

HANDLER_READ_WRITE_EDIT = '''

def _tool_read(path: str, limit: int | None = None) -> str:
    try:
        text = safe_path(path).read_text(encoding="utf-8")
        lines = text.splitlines()
        if limit is not None:
            lines = lines[:limit]
        return "\\n".join(lines)
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"


def _tool_write(path: str, content: str) -> str:
    try:
        safe = safe_path(path)
        safe.parent.mkdir(parents=True, exist_ok=True)
        safe.write_text(content, encoding="utf-8")
        return f"Wrote {len(content)} bytes to {path}"
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"


def _tool_edit(path: str, old_text: str, new_text: str) -> str:
    try:
        safe = safe_path(path)
        text = safe.read_text(encoding="utf-8")
        if old_text not in text:
            return f"Error: text not found in {path}"
        safe.write_text(text.replace(old_text, new_text, 1), encoding="utf-8")
        return f"Edited {path}"
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"
'''

HANDLER_TODO = '''

_CURRENT_TODOS: list[dict] = []


def _tool_todo_write(todos: str) -> str:
    """Update the plan. todos must be a JSON array of {content, status}."""
    try:
        parsed = json.loads(todos)
    except json.JSONDecodeError:
        return "Error: todos must be a JSON array string"
    if not isinstance(parsed, list):
        return "Error: todos must be a list"
    for i, item in enumerate(parsed):
        if not isinstance(item, dict) or "content" not in item or "status" not in item:
            return f"Error: todos[{i}] missing 'content' or 'status'"
        if item["status"] not in ("pending", "in_progress", "completed"):
            return f"Error: todos[{i}] has invalid status"
    _CURRENT_TODOS[:] = parsed
    return f"Updated {len(parsed)} todos"
'''

HANDLER_SUBAGENT = '''

def _tool_spawn_subagent(prompt: str) -> str:
    """Run a subtask in a fresh message list; return its final text."""
    try:
        return agent_loop(prompt, history=None)
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"
'''

HANDLER_SKILL = '''

SKILLS_DIR = WORKDIR / "skills"


def _scan_skills() -> dict:
    skills = {}
    if not SKILLS_DIR.exists():
        return skills
    for directory in sorted(SKILLS_DIR.iterdir()):
        manifest = directory / "SKILL.md"
        if manifest.exists() and directory.is_dir():
            raw = manifest.read_text(encoding="utf-8")
            lines = raw.splitlines()
            desc = ""
            for line in lines:
                if line.startswith("description:"):
                    desc = line.split(":", 1)[1].strip()
                    break
            skills[directory.name] = {"name": directory.name, "description": desc, "content": raw}
    return skills


def _tool_list_skills() -> str:
    skills = _scan_skills()
    if not skills:
        return "(no skills found)"
    return "\\n".join(f"- {name}: {meta['description']}" for name, meta in skills.items())


def _tool_load_skill(name: str) -> str:
    skills = _scan_skills()
    skill = skills.get(name)
    if not skill:
        return f"Skill not found: {name}. Available: {', '.join(skills) or '(none)'}"
    return skill["content"]
'''

# ===========================================================================
# Tool registry per level (name -> (description, schema, permission))
# ===========================================================================


def tool_specs_for(level: int) -> str:
    """Return the TOOL_SPECS dict literal for the given level."""
    entries = [
        ('    "bash": Tool(\n'
         '        name="bash",\n'
         '        description="Execute a shell command.",\n'
         '        input_schema={"type": "object", "properties": {"command": {"type": "string"}}, "required": ["command"]},\n'
         '        handler=_tool_bash,\n'
         '        permission="allow",\n'
         '    ),'),
    ]
    if level >= 1:
        entries += [
            ('    "read_file": Tool(\n'
             '        name="read_file",\n'
             '        description="Read a text file\'s contents.",\n'
             '        input_schema={"type": "object", "properties": {"path": {"type": "string"}, "limit": {"type": "integer"}}, "required": ["path"]},\n'
             '        handler=_tool_read,\n'
             '        permission="allow",\n'
             '    ),'),
            ('    "write_file": Tool(\n'
             '        name="write_file",\n'
             '        description="Write content to a file.",\n'
             '        input_schema={"type": "object", "properties": {"path": {"type": "string"}, "content": {"type": "string"}}, "required": ["path", "content"]},\n'
             '        handler=_tool_write,\n'
             '        permission="ask",\n'
             '    ),'),
            ('    "edit_file": Tool(\n'
             '        name="edit_file",\n'
             '        description="Replace exact text in a file.",\n'
             '        input_schema={"type": "object", "properties": {"path": {"type": "string"}, "old_text": {"type": "string"}, "new_text": {"type": "string"}}, "required": ["path", "old_text", "new_text"]},\n'
             '        handler=_tool_edit,\n'
             '        permission="ask",\n'
             '    ),'),
        ]
    if level >= 2:
        entries.append(
            ('    "todo_write": Tool(\n'
             '        name="todo_write",\n'
             '        description="Update the plan. Pass a JSON array of {content, status} items.",\n'
             '        input_schema={"type": "object", "properties": {"todos": {"type": "string"}}, "required": ["todos"]},\n'
             '        handler=_tool_todo_write,\n'
             '        permission="allow",\n'
             '    ),')
        )
    if level >= 3:
        entries.append(
            ('    "spawn_subagent": Tool(\n'
             '        name="spawn_subagent",\n'
             '        description="Run a subtask in a fresh message list and return its final text.",\n'
             '        input_schema={"type": "object", "properties": {"prompt": {"type": "string"}}, "required": ["prompt"]},\n'
             '        handler=_tool_spawn_subagent,\n'
             '        permission="allow",\n'
             '    ),')
        )
    if level >= 4:
        entries += [
            ('    "list_skills": Tool(\n'
             '        name="list_skills",\n'
             '        description="List available skills.",\n'
             '        input_schema={"type": "object", "properties": {}},\n'
             '        handler=_tool_list_skills,\n'
             '        permission="allow",\n'
             '    ),'),
            ('    "load_skill": Tool(\n'
             '        name="load_skill",\n'
             '        description="Load a skill\'s full content by name.",\n'
             '        input_schema={"type": "object", "properties": {"name": {"type": "string"}}, "required": ["name"]},\n'
             '        handler=_tool_load_skill,\n'
             '        permission="allow",\n'
             '    ),'),
        ]
    return "\n".join(entries)


# ===========================================================================
# System prompt extra rules per level
# ===========================================================================


def system_rules_for(level: int) -> str:
    rules = ["- Prefer action over explanation.",
             "- Never invent file paths; read first if unsure.",
             "- After finishing, summarize what changed."]
    if level >= 2:
        rules.append("- For multi-step work, call todo_write first to lay out the plan.")
    if level >= 3:
        rules.append("- For noisy or isolated subtasks, use spawn_subagent instead of inline work.")
    if level >= 4:
        rules.append("- List skills with list_skills, then load_skill(name) only when relevant.")
    return "\n".join(rules)


def tool_names_for(level: int) -> str:
    names = ["bash"]
    if level >= 1:
        names += ["read_file", "write_file", "edit_file"]
    if level >= 2:
        names.append("todo_write")
    if level >= 3:
        names.append("spawn_subagent")
    if level >= 4:
        names += ["list_skills", "load_skill"]
    return ", ".join(names)


# ===========================================================================
# Core loop (common tail, with placeholders filled by build_agent_source)
# ===========================================================================

CORE = '''

def permission_check(tool: Tool, args: dict) -> str:
    """Return "allow", "ask", or "deny" for a tool call.

    Override with your product's permission rules (see s03). Default is
    conservative: anything marked "ask" requires human consent.
    """
    if tool.permission == "deny":
        return "deny"
    if tool.permission == "ask":
        answer = input(f"  [permission] Allow {tool.name}({str(args)[:80]})? [y/N] ")
        return "allow" if answer.strip().lower() in {"y", "yes"} else "deny"
    return "allow"


SYSTEM_PROMPT = f"""You are a coding agent working in {WORKDIR}.

Rules:
{rules}

Tools: {tool_names}.
"""


def _backoff(attempt: int) -> float:
    return CONFIG["base_delay_seconds"] * (2 ** attempt)


def call_model(messages: list[dict]) -> Any:
    """Call the model with retry on transient errors and timeout."""
    last_error: Exception | None = None
    for attempt in range(CONFIG["max_retries"]):
        try:
            return client.messages.create(
                model=CONFIG["model"],
                system=SYSTEM_PROMPT,
                messages=messages,
                tools=TOOL_DEFS,
                max_tokens=CONFIG["max_tokens"],
                timeout=CONFIG["timeout_seconds"],
            )
        except (APITimeoutError, APIConnectionError, APIStatusError) as exc:
            last_error = exc
            delay = _backoff(attempt)
            LOG.warning("model call failed (attempt %d/%d): %s; retry in %.1fs",
                        attempt + 1, CONFIG["max_retries"], exc, delay)
            time.sleep(delay)
    raise RuntimeError(f"Model call failed after {CONFIG['max_retries']} attempts: {last_error}")


def record_trajectory(entry: dict) -> None:
    """Append one step to the trajectory log (training signal for the future)."""
    try:
        TRAJECTORY_DIR.mkdir(parents=True, exist_ok=True)
        path = TRAJECTORY_DIR / f"trajectory-{time.strftime('%Y%m%d')}.jsonl"
        with path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(entry, ensure_ascii=True) + "\\n")
    except Exception as exc:  # noqa: BLE001
        LOG.warning("failed to record trajectory: %s", exc)


def agent_loop(prompt: str, history: list[dict] | None = None) -> str:
    history = history if history is not None else []
    history.append({"role": "user", "content": prompt})

    while True:
        response = call_model(history)
        history.append({"role": "assistant", "content": response.content})

        tool_calls = [b for b in response.content if getattr(b, "type", None) == "tool_use"]
        if not tool_calls:
            return "".join(
                b.text for b in response.content if getattr(b, "type", None) == "text"
            )

        results = []
        for block in tool_calls:
            tool = TOOL_SPECS.get(block.name)
            if tool is None:
                output = f"Unknown tool: {block.name}"
            else:
                try:
                    args = _validate_input(tool, dict(block.input))
                    decision = permission_check(tool, args)
                    if decision == "deny":
                        output = f"Permission denied for {tool.name}"
                    else:
                        output = tool.handler(**args)
                except Exception as exc:  # noqa: BLE001
                    output = f"Error: {type(exc).__name__}: {exc}"
                record_trajectory({
                    "ts": time.time(),
                    "tool": block.name,
                    "input": block.input,
                    "output": output[:1000],
                })
            LOG.info("tool=%s output=%s", block.name, output[:120])
            results.append({
                "type": "tool_result",
                "tool_use_id": block.id,
                "content": output,
            })

        history.append({"role": "user", "content": results})


def _shutdown(signum, _frame):
    LOG.info("received signal %s, shutting down", signum)
    sys.exit(128 + signum)


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    signal.signal(signal.SIGTERM, _shutdown)
    signal.signal(signal.SIGINT, _shutdown)

    LOG.info("agent started; model=%s workdir=%s", CONFIG["model"], WORKDIR)
    print(f"Agent ready. Model: {CONFIG['model']}. Type 'q' to quit.\\n")

    history: list[dict] = []
    while True:
        try:
            query = input(">> ").strip()
        except (EOFError, KeyboardInterrupt):
            break
        if query in {"q", "quit", "exit", ""}:
            break
        try:
            print(agent_loop(query, history))
        except Exception as exc:  # noqa: BLE001
            LOG.error("agent loop failed: %s", exc)
            print(f"Error: {exc}")
        print()


if __name__ == "__main__":
    main()
'''


LEVEL_DESCRIPTIONS = {
    0: "agent loop + bash",
    1: "4 tools, production base",
    2: "+ TodoWrite planning",
    3: "+ Subagent",
    4: "+ Skill loading",
}


def build_agent_source(name: str, level: int) -> str:
    """Assemble the full agent.py source for a name and level."""
    handlers = [HANDLER_BASH]
    if level >= 1:
        handlers.append(HANDLER_READ_WRITE_EDIT)
    if level >= 2:
        handlers.append(HANDLER_TODO)
    if level >= 3:
        handlers.append(HANDLER_SUBAGENT)
    if level >= 4:
        handlers.append(HANDLER_SKILL)

    source = COMMON_HEADER.format(
        name=name, level=level, level_desc=LEVEL_DESCRIPTIONS[level]
    )
    source += "".join(handlers)
    source += "\n\nTOOL_SPECS: dict[str, Tool] = {\n" + tool_specs_for(level) + "\n}\n"
    source += (
        "\nTOOL_DEFS = [\n"
        "    {\"name\": t.name, \"description\": t.description, \"input_schema\": t.input_schema}\n"
        "    for t in TOOL_SPECS.values()\n"
        "]\n"
    )
    # fill the CORE placeholders: {rules} and {tool_names}
    source += CORE.replace("{rules}", system_rules_for(level)).replace(
        "{tool_names}", tool_names_for(level)
    )
    return source


# ===========================================================================
# Other generated files
# ===========================================================================

ENV_TEMPLATE = """# API Key (required)
ANTHROPIC_API_KEY=sk-ant-xxx

# Model ID (required)
MODEL_ID=claude-sonnet-4-6

# Base URL (optional, for Anthropic-compatible providers)
# ANTHROPIC_BASE_URL=https://api.anthropic.com

# --- Tuning (optional, overrides config.yaml) ---
# MAX_TOKENS=8000
# TIMEOUT_SECONDS=120
# MAX_RETRIES=3
# BASE_DELAY_SECONDS=0.5
"""

CONFIG_TEMPLATE = """# Declarative config. Environment variables take precedence.

model: claude-sonnet-4-6
max_tokens: 8000
timeout_seconds: 120
max_retries: 3
base_delay_seconds: 0.5
"""

REQUIREMENTS_TEMPLATE = """anthropic>=0.25.0
python-dotenv>=1.0.0
pyyaml>=6.0
"""

README_TEMPLATE = """# {name}

Production Agent project (level {level}: {level_desc}), generated by `init_agent.py`.

## Run

```sh
pip install -r requirements.txt
cp .env.example .env      # fill in ANTHROPIC_API_KEY
cp config.example.yaml config.yaml  # optional
python agent.py
```

## Customize for your domain

1. Replace the tool handlers in `agent.py` (`_tool_*` functions) with your domain tools.
2. Edit `TOOL_SPECS` to register them (name / description / schema / permission).
3. Rewrite `SYSTEM_PROMPT` with your agent's identity, rules, and knowledge catalog.
4. Override `permission_check()` with your approval/deny rules.

## Next steps

- Harden: add context compaction (s08), memory (s09), or tasks (s10) as your PRD demands.
- See the repository `BLUEPRINT.md` for the full component library and derivation SOP.
"""


def create_agent(name: str, level: int, output_dir: Path) -> None:
    if level not in LEVEL_DESCRIPTIONS:
        print(f"Error: level must be one of {sorted(LEVEL_DESCRIPTIONS)}")
        sys.exit(1)

    agent_dir = output_dir / name
    agent_dir.mkdir(parents=True, exist_ok=True)

    (agent_dir / "agent.py").write_text(build_agent_source(name, level), encoding="utf-8")
    (agent_dir / ".env.example").write_text(ENV_TEMPLATE, encoding="utf-8")
    (agent_dir / "config.example.yaml").write_text(CONFIG_TEMPLATE, encoding="utf-8")
    (agent_dir / "requirements.txt").write_text(REQUIREMENTS_TEMPLATE, encoding="utf-8")
    (agent_dir / "README.md").write_text(
        README_TEMPLATE.format(name=name, level=level, level_desc=LEVEL_DESCRIPTIONS[level]),
        encoding="utf-8",
    )

    print(f"Created production Agent project '{name}' at {agent_dir}")
    print("Files: agent.py, config.example.yaml, .env.example, requirements.txt, README.md")
    print("\nNext steps:")
    print(f"  1. cd {agent_dir}")
    print("  2. pip install -r requirements.txt")
    print("  3. cp .env.example .env   # fill in ANTHROPIC_API_KEY")
    print("  4. python agent.py")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Scaffold a production-grade Agent project",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Levels:
  0  Agent loop + bash            — minimum viable agent
  1  + read/write/edit tools      — production base (config, logging, retry, permission, trajectory)
  2  + TodoWrite                  — plan first, then execute
  3  + Subagent                   — isolated context for subtasks
  4  + Skill loading              — on-demand domain knowledge
        """,
    )
    parser.add_argument("name", help="Name of the agent project to create")
    parser.add_argument("--level", type=int, default=1, choices=[0, 1, 2, 3, 4],
                        help="Complexity level (default: 1)")
    parser.add_argument("--path", type=Path, default=Path.cwd(),
                        help="Output directory (default: current directory)")

    args = parser.parse_args()
    create_agent(args.name, args.level, args.path)


if __name__ == "__main__":
    main()
